### ISSUE TITLE
devSetup Python script fails after installing node

### ISSUE THREAD

**Issue by dariusf** [codecombat/codecombat#1374]
When following the instructions [here](https://github.com/codecombat/codecombat/wiki/Developer-environment) (Ubuntu 14.04) with a clean clone of the repository, the Python script fails to complete.

Here's the console output:

```
...
unbuild npm@1.4.21
/home/darius/local/bin/npm -> /home/darius/local/lib/node_modules/npm/bin/npm-cli.js
npm@1.4.21 /home/darius/local/lib/node_modules/npm
It worked
Updated npm version installed
Installing node packages...
Traceback (most recent call last):
  File "./coco/scripts/devSetup/setup.py", line 46, in <module>
    setup.setup()
  File "/home/darius/coco/coco/scripts/devSetup/factories.py", line 88, in setup
    super(self.__class__, self).setup()
  File "/home/darius/coco/coco/scripts/devSetup/factories.py", line 51, in setup
    self.repoCloner.install_node_packages()
  File "/home/darius/coco/coco/scripts/devSetup/repositoryInstaller.py", line 67, in install_node_packages
    return_code = subprocess.call([npm_location,u"install"],cwd=self.config.directory.root_dir + os.sep + u"coco")
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by nwinter** [comment]
Closing for now; not sure what the exact issue is or what we can do about it.
