### ISSUE TITLE
"Non-UserCodeError: TypeError: Cannot read property 'length'" of undefined when simulating

### ISSUE THREAD

**Issue by yaur** [codecombat/codecombat#2213]
From JS console:
------------------------------------------------------------
|Thanatos's Lana| Generated random seed 5717210963 of type submissionCount from sessionIDs 54c551b13e62e3210d4f080f,54cf19eaad25d155057ed830 submissionCount undefined
Angel.coffee:47 |Thanatos's Lana| Non-UserCodeError: TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at t.eval (eval at <anonymous> (http://codecombat.com/javascripts/world.js:323:20), <anonymous>:48:32)
    at t.Electrocutes.performElectrocute (eval at <anonymous> (http://codecombat.com/javascripts/world.js:323:20), <anonymous>:55:8)
    at t.Electrocutes.update (eval at <anonymous> (http://codecombat.com/javascripts/world.js:323:20), <anonymous>:84:17)
    at t.e.exports.t.callChainedMethod (http://codecombat.com/javascripts/world.js:216:191)
    at t.r [as update] (http://codecombat.com/javascripts/lodash.js:50:27)
    at Existence.update (eval at <anonymous> (http://codecombat.com/javascripts/world.js:323:20), <anonymous>:69:15)
    at t.e.exports.t.getNextFrame (http://codecombat.com/javascripts/world.js:385:100)
    at World.module.exports.World.getFrame (http://codecombat.com/javascripts/world.js:287:52)
    at World.module.exports.World.loadFrames (http://codecombat.com/javascripts/world.js:296:10)
    at http://codecombat.com/javascripts/world.js:293:172
17Simulator.coffee:79 There was an infinite loop in the single game!
Simulator.coffee:238 Skipping infinitely looping game.
-------------------------------------------------------------------
playing [this match](https://codecombat.com/play/level/cavern-survival?team=ogres&opponent=54c551b13e62e3210d4f080f) normally doesn't result in anything odd being written to the event log, though looking at the session it looks like they are trying to cast electrocute, but don't have the spell.

**Comment by nwinter** [comment]
How about now? I just updated Electrocute to error out earlier when cast on an invalid target.

**Comment by yaur** [comment]
Is there an easy way to sim a specific session? If so I can retest.

**Comment by nwinter** [comment]
Ah, right; not too easily. I think I have fixed it, so I'll close this, but let's keep our eyes out.

**Comment by yaur** [comment]
Verified as fixed.
