### ISSUE TITLE
Reduce Stripe API request rate for subscription server tests

### ISSUE THREAD

**Issue by differentmatt** [codecombat/codecombat#2588]
For test case 'Unsubscribed user1 subscribes 13 users, unsubcribes 2', saw the below error.  The test case also still passed, so we need to look into that as well.

```sh
PUT /db/user 200 86705ms
Error updating stripe customer... { [Error: Request rate limit exceeded]
  type: 'StripeInvalidRequest',
  stack: 'Error: Request rate limit exceeded\n  at Error._Error (/Users/matt/GitHub/codecombat/node_modules/stripe/lib/Error.js:12:17)\n  at Error.Constructor (/Users/matt/GitHub/codecombat/node_modules/stripe/lib/utils.js:90:13)\n  at Error.Constructor (/Users/matt/GitHub/codecombat/node_modules/stripe/lib/utils.js:90:13)\n  at Function.StripeError.generate (/Users/matt/GitHub/codecombat/node_modules/stripe/lib/Error.js:56:14)\n  at IncomingMessage.<anonymous> (/Users/matt/GitHub/codecombat/node_modules/stripe/lib/StripeResource.js:124:39)\n  at IncomingMessage.emit (events.js:117:20)\n  at _stream_readable.js:943:16\n  at process._tickDomainCallback (node.js:463:13)\n',
  rawType: 'invalid_request_error',
  code: 'rate_limit',
  param: undefined,
  message: 'Request rate limit exceeded',
  detail: undefined,
  raw: 
   { type: 'invalid_request_error',
     message: 'Request rate limit exceeded',
     code: 'rate_limit' } }
```

**Comment by differentmatt** [comment]
https://github.com/codecombat/codecombat/commit/865ceac91a7a5ab5e560e86464595f6a1948b311
https://github.com/codecombat/codecombat/commit/981298665537ce51014a3886ab173a6fc0204653
