### ISSUE TITLE
Can't always find stripe chargeID in payments

### ISSUE THREAD

**Issue by nwinter** [codecombat/codecombat#2793]
Saw workers die on [this line](https://github.com/codecombat/codecombat/blob/master/server/payments/payment_handler.coffee#L338-L338) of `checkStripeCharges` in `payment_handler.coffee`:

```coffeescript
        recordedChargeIDs = (p.get('stripe').chargeID for p in payments)
```

```
May 28 12:39:28 ip-10-0-0-14 multicore.log:  /home/ubuntu/codecombat/node_modules/newrelic/lib/transaction/tracer/index.js:168
May 28 12:39:28 ip-10-0-0-14 multicore.log:        throw err
May 28 12:39:28 ip-10-0-0-14 multicore.log:              ^
May 28 12:39:28 ip-10-0-0-14 multicore.log:  TypeError: Cannot read property 'chargeID' of undefined
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at /home/ubuntu/codecombat/server/payments/payment_handler.coffee:338:45
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at /home/ubuntu/codecombat/server/payments/payment_handler.coffee:457:13
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at /home/ubuntu/codecombat/node_modules/async/lib/async.js:232:13
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at /home/ubuntu/codecombat/node_modules/async/lib/async.js:119:25
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at /home/ubuntu/codecombat/node_modules/async/lib/async.js:24:16
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at /home/ubuntu/codecombat/node_modules/async/lib/async.js:229:17
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at /home/ubuntu/codecombat/node_modules/async/lib/async.js:516:34
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at async.parallel.payments (/home/ubuntu/codecombat/server/payments/payment_handler.coffee:327:13)
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at [object Object].<anonymous> (/home/ubuntu/codecombat/node_modules/stripe/lib/StripeResource.js:78:34)
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at [object Object].wrappedCallback (/home/ubuntu/codecombat/node_modules/newrelic/lib/transaction/tracer/index.js:338:23)
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at [object Object].wrapped (/home/ubuntu/codecombat/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at [object Object].wrappedCallback (/home/ubuntu/codecombat/node_modules/newrelic/lib/transaction/tracer/index.js:429:66)
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at [object Object].wrapped [as _onTimeout] (/home/ubuntu/codecombat/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
May 28 12:39:28 ip-10-0-0-14 multicore.log:    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
May 28 12:39:28 ip-10-0-0-14 multicore.log:  Worker 3 died! Squished under a boulder.
```

**Comment by differentmatt** [comment]
Closing due to issues age.  Can revisit if this shows up again.
