### ISSUE TITLE
crash: SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by xrfang** [codecombat/codecombat#3437]
I followed the Linux get started guide, cannot boot up the server info below. 

GIT REVISION: 

bada484 2016-03-02 16:19:33 -0800 | Fix fetchPatchesWithStatus for non-versioned models (HEAD, origin/master, origin/HEAD, master) [Nick Winter]

Environment: 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"

Linux Desktop 3.19.0-49-generic #55-Ubuntu SMP Fri Jan 22 02:10:24 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

ERROR MESSAGE:

> codecombat@ dev /home/xrfang/git/codecombat
> brunch watch --server

Got 465 coffee files and 211 jade files (bundled 89 of them together).
03 Mar 10:01:53 - info: custom server started, initializing watcher
3 Mar 10:01:53 - [nodemon] v1.6.1
3 Mar 10:01:53 - [nodemon] reading config /home/xrfang/git/codecombat/nodemon.json
3 Mar 10:01:53 - [nodemon] to restart at any time, enter `rs`
3 Mar 10:01:53 - [nodemon] ignoring: /home/xrfang/git/codecombat/.git/**/* /home/xrfang/git/codecombat/node_modules/**/* /home/xrfang/git/codecombat/bower_components/**/* .sass-cache
3 Mar 10:01:53 - [nodemon] watching: server_config.js server_setup.coffee /home/xrfang/git/codecombat/app/schemas/**/* /home/xrfang/git/codecombat/server/**/*
3 Mar 10:01:53 - [nodemon] watching extensions: js,coffee
3 Mar 10:01:53 - [nodemon] starting `node .`
3 Mar 10:01:53 - [nodemon] child pid: 3009
3 Mar 10:01:53 - [nodemon] watching 172 files
SENDWITHUS: Debug enabled

/home/xrfang/git/codecombat/server/middleware/files.coffee:21
      return wrap(function*(req, res) {
                          ^
SyntaxError: Unexpected token *
  at Module._compile (module.js:439:25)
  at Object.loadFile (/home/xrfang/git/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/xrfang/git/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/xrfang/git/codecombat/server/middleware/index.coffee:3:10)
  at Object.<anonymous> (/home/xrfang/git/codecombat/server/middleware/index.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/home/xrfang/git/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/xrfang/git/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/xrfang/git/codecombat/server/routes/index.coffee:1:6)
  at Object.<anonymous> (/home/xrfang/git/codecombat/server/routes/index.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/home/xrfang/git/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/xrfang/git/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/xrfang/git/codecombat/server_setup.coffee:17:10)
  at Object.<anonymous> (/home/xrfang/git/codecombat/server_setup.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/home/xrfang/git/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/xrfang/git/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/xrfang/git/codecombat/server.coffee:11:15)
  at Object.<anonymous> (/home/xrfang/git/codecombat/server.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/home/xrfang/git/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/xrfang/git/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/xrfang/git/codecombat/index.js:3:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3

**Comment by nwinter** [comment]
What version of node are you using? It looks like it's old enough to not have support for generator functions. Try updating node and then deleting and reinstalling the node modules.

**Comment by UltCombo** [comment]
It looks like you're using an outdated version of Node.js. Try updating to latest (v5.7.0).

**Comment by UltCombo** [comment]
@nick beat me to it in the same minute hahah. :sweat_smile:
