### ISSUE TITLE
Cannot view matches with opponent

### ISSUE THREAD

**Issue by rossdrew** [codecombat/codecombat#3672]
[_I've already mailed support regarding this but issues might be easier to track_]

Recently (last couple of weeks) I've stopped being able to review matches against opponents.  Any URL containing an "opponent" such as...

[https://codecombat.com/play/level/cavern-survival?team=humans&opponent=5702738c263b0220002c8442](https://codecombat.com/play/level/cavern-survival?team=humans&opponent=5702738c263b0220002c8442)

results in a freeze, just as the progress bar completes, this looks like the relevant stack trace:-
```
|Thoth's Krieger| couldn't load components for 529ffbf1cf1818f2be000001 Hero Placeholder 1 because SyntaxError: Unexpected token u SyntaxError: Unexpected token u
    at Object.parse (native)
    at Function.t (https://codecombat.com/javascripts/esper.js:4663:212)
    at e.s (https://codecombat.com/javascripts/esper.js:50:55)
    at e.u (https://codecombat.com/javascripts/esper.js:47:56)
    at Object.e.exports.createFunction (https://codecombat.com/javascripts/aether.js:6369:23)
    at e.exports.e.createFunction (https://codecombat.com/javascripts/aether.js:6177:42)
    at t.Programmable.replaceMethodCode (eval at <anonymous> (https://codecombat.com/javascripts/world.js:1178:35), <anonymous>:158:20)
    at t.Programmable.deserializeAether (eval at <anonymous> (https://codecombat.com/javascripts/world.js:1178:35), <anonymous>:127:10)
    at Programmable.attach (eval at <anonymous> (https://codecombat.com/javascripts/world.js:1178:35), <anonymous>:62:27)
    at t.e.exports.t.addComponents (https://codecombat.com/javascripts/world.js:731:10)
    at World.module.exports.World.loadThangFromLevel (https://codecombat.com/javascripts/world.js:1165:21)
    at World.<anonymous> (https://codecombat.com/javascripts/world.js:1149:13)
    at World.module.exports.World.loadThangsFromLevel (https://codecombat.com/javascripts/world.js:1149:77)
    at World.module.exports.World.loadFromLevel (https://codecombat.com/javascripts/world.js:1125:6)
    at a (https://codecombat.com/javascripts/workers/worker_world.js:116:23)
    at DedicatedWorkerGlobalScope.<anonymous> (https://codecombat.com/javascripts/workers/worker_world.js:178:62)
```

This happens on my Fedora 23, Windows 10 and Windows 8 machines on all browsers (Firefox, Chrome, Safari, Explorer, Edge, Tor)

**Comment by leorlf2h** [comment]
https://discourse.codecombat.com/t/ladder-replays-not-loading/7707

It has been solved in this topic.
You can try it again. :)

**Comment by rossdrew** [comment]
Thanks, I had a look around but didn't see that.
