### ISSUE TITLE
Jasmine test failing out of the box

### ISSUE THREAD

**Issue by ogennadi** [codecombat/codecombat#4374]
I did a fresh checkout out the Coco repo, and when I ran `npm run jasmine` one test failed. FYI I'm running Ubuntu 16.04.

```
1) DELETE /db/prepaid/:handle/redeemers works if the user has not migrated from coursePrepaidID to coursePrepaid
  Message:
    Failed: Cannot read property 'length' of undefined
  Stack:
    TypeError: Cannot read property 'length' of undefined
      at Object.<anonymous> (/home/codecombat/codecombat/spec/server/functional/prepaid.spec.coffee:475:26)
      at [object Generator].next (native)
      at onFulfilled (/home/codecombat/codecombat/node_modules/co/index.js:65:19)
      at tryCatcher (/home/codecombat/codecombat/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/codecombat/codecombat/node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (/home/codecombat/codecombat/node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (/home/codecombat/codecombat/node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (/home/codecombat/codecombat/node_modules/bluebird/js/release/promise.js:693:18)
      at Promise._fulfill (/home/codecombat/codecombat/node_modules/bluebird/js/release/promise.js:638:18)
      at Request._callback (/home/codecombat/codecombat/node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (/home/codecombat/codecombat/node_modules/request/request.js:188:22)
      at emitTwo (events.js:100:13)
      at Request.emit (events.js:185:7)
      at Request.<anonymous> (/home/codecombat/codecombat/node_modules/request/request.js:1171:10)
      at emitOne (events.js:90:13)
      at Request.emit (events.js:182:7)
      at IncomingMessage.<anonymous> (/home/codecombat/codecombat/node_modules/request/request.js:1091:12)
      at IncomingMessage.g (events.js:273:16)
      at emitNone (events.js:85:20)
      at IncomingMessage.emit (events.js:179:7)
      at endReadableNT (_stream_readable.js:913:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by ogennadi** [comment]
Issue still present as at cacb7fa56ecddadca98b92966b909cebea00d5ce

**Comment by sderickson** [comment]
Fixed in https://github.com/codecombat/codecombat/commit/51c2a79
