### ISSUE TITLE
Cannot find module '../../bower_components/treema/treema-utils.js'

### ISSUE THREAD

**Issue by edutrul** [codecombat/codecombat#4443]
Hi I am getting Cannot find module '../../bower_components/treema/treema-utils.js' error
when running npm start

I have tried this with
node v6.11.3
also did try with v8 and v4
what am I doing wrong? this worked on my local but on my vps
thanks in advance!

# npm start

> codecombat@ start /var/www/html/Code-heroes
> node ./index.js

module.js:471
    throw err;
    ^

Error: Cannot find module '../../bower_components/treema/treema-utils.js'
  at Function.Module._resolveFilename (module.js:469:15)
  at Function.Module._load (module.js:417:25)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)

**Comment by takima** [comment]
Did you solve your problem ?  I encounter with the same error !  I found that this error occur recently. So I doubt it is relative with new update. Hoping the author can help us to figure out it.

**Comment by sderickson** [comment]
What happens if you run `bower install`?
