### ISSUE TITLE
When I tried to run start, it gave me the following error

### ISSUE THREAD

**Issue by cuiyimeng** [codecombat/codecombat#4579]
module.js:471
    throw err;
    ^

Error: Cannot find module '../../bower_components/treema/treema-utils.js'
  at Function.Module._resolveFilename (module.js:469:15)
  at Function.Module._load (module.js:417:25)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/cym/codecombat/server/models/Achievement.coffee:7:15)
  at Object.<anonymous> (/home/cym/codecombat/server/models/Achievement.coffee:1:1)
  at Module._compile (module.js:570:32)
  at Object.loadFile (/home/cym/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/cym/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at AchievablePlugin (/home/cym/codecombat/server/plugins/achievements.coffee:13:17)
  at Schema.plugin (/home/cym/codecombat/node_modules/mongoose/lib/schema.js:1231:3)
  at Object.<anonymous> (/home/cym/codecombat/server/models/User.coffee:628:12)
  at Object.<anonymous> (/home/cym/codecombat/server/models/User.coffee:1:1)
  at Module._compile (module.js:570:32)
  at Object.loadFile (/home/cym/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/cym/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/cym/codecombat/server/commons/auth.coffee:3:8)
  at Object.<anonymous> (/home/cym/codecombat/server/commons/auth.coffee:1:1)
  at Module._compile (module.js:570:32)
  at Object.loadFile (/home/cym/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/cym/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/cym/codecombat/server_setup.coffee:17:8)
  at Object.<anonymous> (/home/cym/codecombat/server_setup.coffee:1:1)
  at Module._compile (module.js:570:32)
  at Object.loadFile (/home/cym/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/cym/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/cym/codecombat/server.coffee:11:15)
  at Object.<anonymous> (/home/cym/codecombat/server.coffee:1:1)
  at Module._compile (module.js:570:32)
  at Object.loadFile (/home/cym/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/cym/codecombat/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/cym/codecombat/index.js:11:14)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! codecombat@ start: `node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the codecombat@ start script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the codecombat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs codecombat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls codecombat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cym/codecombat/npm-debug.log

**Comment by nwinter** [comment]
Try running it on node 5.12, and also, after you are on that node version, reinstall all node packages with `npm install`. Node 6 is not supported at the moment.

**Comment by GaleaWong** [comment]
I'm the same problem.
