### ISSUE TITLE
Kithgard Brawl Non-User code error

### ISSUE THREAD

**Issue by jasonpnnl** [codecombat/codecombat#4634]
Getting the following errors in Kithgard Brawl. Sometimes will not successfully load at all. Other times will load but then level will freeze part way in.

|Loki's Cyril| distance from Wolf Pup Pet to undefined did not work: isVector undefined isThang undefined x undefined y undefined keys 
Angel.coffee:58 |Loki's Cyril| Non-UserCodeError: `distance`'s argument `target` should have type `object`, but got `null`.
Find the distance to a target unit.
ArgumentError: Find the distance to a target unit.
    at Thang.Physical.distance (eval at 48.module.exports.World.loadClassFromCode (https://codecombat.com/javascripts/world.js:32655:21), <anonymous>:70:13)
    at Thang.Fetches.update (eval at 48.module.exports.World.loadClassFromCode (https://codecombat.com/javascripts/world.js:32655:21), <anonymous>:51:43)
    at Thang.33.module.exports.Thang.callChainedMethod (https://codecombat.com/javascripts/world.js:28578:30)
    at Thang.bound [as update] (https://codecombat.com/javascripts/world.js:10245:21)
    at Existence.update (eval at 48.module.exports.World.loadClassFromCode (https://codecombat.com/javascripts/world.js:32655:21), <anonymous>:91:15)
    at WorldFrame.38.module.exports.WorldFrame.getNextFrame (https://codecombat.com/javascripts/world.js:29215:27)
    at World.48.module.exports.World.getFrame (https://codecombat.com/javascripts/world.js:32177:38)
    at World.48.module.exports.World.loadFrames (https://codecombat.com/javascripts/world.js:32308:14)
    at https://codecombat.com/javascripts/world.js:32254:24

**Comment by jasonpnnl** [comment]
Appears to be present only when having a pet equipped. When pet is unequipped there is no error.

**Comment by Bryukh** [comment]
I've found one place where this error should be and I've added checkings to prevent it. Thanks!
