### ISSUE TITLE
Who can help me？not find treema-utils.js

### ISSUE THREAD

**Issue by GaleaWong** [codecombat/codecombat#4654]
module.js:341
    throw err;
    ^

Error: Cannot find module '../../bower_components/treema/treema-utils.js'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/hnck/codecombat-master/server/models/Achievement.coffee:7:15)
  at Object.<anonymous> (/home/hnck/codecombat-master/server/models/Achievement.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/home/hnck/codecombat-master/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/hnck/codecombat-master/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:20:19)
  at AchievablePlugin (/home/hnck/codecombat-master/server/plugins/achievements.coffee:13:17)
  at Schema.plugin (/home/hnck/codecombat-master/node_modules/mongoose/lib/schema.js:1226:3)
  at Object.<anonymous> (/home/hnck/codecombat-master/server/models/User.coffee:634:12)
  at Object.<anonymous> (/home/hnck/codecombat-master/server/models/User.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/home/hnck/codecombat-master/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/hnck/codecombat-master/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/hnck/codecombat-master/server/commons/auth.coffee:3:8)
  at Object.<anonymous> (/home/hnck/codecombat-master/server/commons/auth.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/home/hnck/codecombat-master/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/hnck/codecombat-master/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/hnck/codecombat-master/server_setup.coffee:17:8)
  at Object.<anonymous> (/home/hnck/codecombat-master/server_setup.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/home/hnck/codecombat-master/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/hnck/codecombat-master/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/hnck/codecombat-master/server.coffee:11:15)
  at Object.<anonymous> (/home/hnck/codecombat-master/server.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/home/hnck/codecombat-master/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/home/hnck/codecombat-master/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/hnck/codecombat-master/index.js:11:14)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Function.Module.runMain (module.js:447:10)
  at startup (node.js:148:18)
  at node.js:405:3

npm ERR! Linux 3.10.0-693.el7.x86_64
npm ERR! argv "/root/.nvm/versions/node/v5.12.0/bin/node" "/root/.nvm/versions/node/v5.12.0/bin/npm" "start"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! codecombat@ start: `node ./index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codecombat@ start script 'node ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the codecombat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs codecombat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls codecombat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hnck/codecombat-master/npm-debug.log

**Comment by nwinter** [comment]
Can you try running under `node 6`? We're not on 5 any more.

**Comment by GaleaWong** [comment]
Thank nwinter very much, but now when I install, there is no public folder.
