### ISSUE TITLE
Please Help me! codecombat@1.0.0 proxy: `COCO_PROXY='true' nodemon`

### ISSUE THREAD

**Issue by SewageFish** [codecombat/codecombat#5059]
Hey guys, I met a problem, I don't understand it and I can't solve it, Could you help me?

I want to build codecombat locally, and this problem arises after I install npm.

```
C:\Users\Easy\codecombat>npm run proxy

> codecombat@1.0.0 proxy C:\Users\Easy\codecombat
> COCO_PROXY='true' nodemon

'COCO_PROXY' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codecombat@1.0.0 proxy: `COCO_PROXY='true' nodemon`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the codecombat@1.0.0 proxy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Easy\AppData\Roaming\npm-cache\_logs\2018-11-30T10_07_05_388Z-debug.log
```

This is the complete log.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Easy\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--userconfig=C:\\Users\\Easy\\.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--registry=https://registry.npm.taobao.org',
1 verbose cli   'run',
1 verbose cli   'proxy' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'preproxy', 'proxy', 'postproxy' ]
5 info lifecycle codecombat@1.0.0~preproxy: codecombat@1.0.0
6 info lifecycle codecombat@1.0.0~proxy: codecombat@1.0.0
7 verbose lifecycle codecombat@1.0.0~proxy: unsafe-perm in lifecycle true
8 verbose lifecycle codecombat@1.0.0~proxy: PATH: C:\Users\Easy\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Easy\codecombat\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\TDM-GCC-64\bin;C:\Program Files\Git\cmd;C:\Users\Easy\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Easy\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\Easy\AppData\Roaming\npm\node_modules\.bin;C:\Python\Scripts\;C:\Python\;C:\Users\Easy\AppData\Local\Microsoft\WindowsApps;C:\Users\Easy\AppData\Roaming\npm;C:\Users\Easy\AppData\Local\Programs\Microsoft VS Code\bin;C:\MinGW
9 verbose lifecycle codecombat@1.0.0~proxy: CWD: C:\Users\Easy\codecombat
10 silly lifecycle codecombat@1.0.0~proxy: Args: [ '/d /s /c', 'COCO_PROXY=\'true\' nodemon' ]
11 silly lifecycle codecombat@1.0.0~proxy: Returned: code: 1  signal: null
12 info lifecycle codecombat@1.0.0~proxy: Failed to exec proxy script
13 verbose stack Error: codecombat@1.0.0 proxy: `COCO_PROXY='true' nodemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Easy\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Easy\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid codecombat@1.0.0
15 verbose cwd C:\Users\Easy\codecombat
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Easy\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\Easy\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "proxy"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error codecombat@1.0.0 proxy: `COCO_PROXY='true' nodemon`
22 error Exit status 1
23 error Failed at the codecombat@1.0.0 proxy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by AndrewJakubowicz** [comment]
Hi @SewageFish ,

What operating system are you using? If you're using windows it may not work due to a different syntax for setting environment variables.
I don't have a windows machine to test but try setting the COCO_PROXY using `set` and then run `nodemon`.

Reference I found when googling how to set environment variables on windows: https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt

**Comment by Bryukh** [comment]
@SewageFish try to use `proxy-win` instead `proxy`

**Comment by SewageFish** [comment]
> @SewageFish try to use `proxy-win` instead `proxy`



> Hi @SewageFish ,
> 
> What operating system are you using? If you're using windows it may not work due to a different syntax for setting environment variables.
> I don't have a windows machine to test but try setting the COCO_PROXY using `set` and then run `nodemon`.
> 
> Reference I found when googling how to set environment variables on windows: https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt

Thank you. You've helped me a lot. I'll try again!

**Comment by Sketti385** [comment]
Does not work, can you please tell me how to "set" and run "nodemon"?
