### ISSUE TITLE
Timeout error + public dir not compiling

### ISSUE THREAD

**Issue by ZJUSTKIDDING** [codecombat/codecombat#6507]
```
ServiceUnavailableError: Response timeout
    at IncomingMessage.<anonymous> (/coco/node_modules/connect-timeout/index.js:84:8)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at Timeout._onTimeout (/coco/node_modules/connect-timeout/index.js:49:11)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

```
Error on entering website ^

Error on build without creating favicon manually:

```
codecombat-master-proxy-1  | Error: ENOENT: no such file or directory, stat '/coco/public/images/favicon/favicon.ico'
codecombat-master-proxy-1  |     at Object.fs.statSync (fs.js:948:11)
codecombat-master-proxy-1  |     at resolveSync (/coco/node_modules/serve-favicon/index.js:187:17)
codecombat-master-proxy-1  |     at favicon (/coco/node_modules/serve-favicon/index.js:61:12)
codecombat-master-proxy-1  |     at setupExpressMiddleware (/coco/server_setup.coffee:91:11)
codecombat-master-proxy-1  |     at Object.exports.setupMiddleware (/coco/server_setup.coffee:206:3)
codecombat-master-proxy-1  |     at module.exports.createAndConfigureApp (/coco/server.coffee:26:15)
codecombat-master-proxy-1  |     at Object.module.exports.startServer (/coco/server.coffee:14:9)
codecombat-master-proxy-1  |     at Object.<anonymous> (/coco/index.js:12:8)
codecombat-master-proxy-1  |     at Module._compile (module.js:653:30)
codecombat-master-proxy-1  |     at Object.Module._extensions..js (module.js:664:10)
codecombat-master-proxy-1  |     at Module.load (module.js:566:32)
codecombat-master-proxy-1  |     at tryModuleLoad (module.js:506:12)
codecombat-master-proxy-1  |     at Function.Module._load (module.js:498:3)
codecombat-master-proxy-1  |     at Function.Module.runMain (module.js:694:10)
codecombat-master-proxy-1  |     at startup (bootstrap_node.js:204:16)
codecombat-master-proxy-1  |     at bootstrap_node.js:625:3

```

**Comment by ZJUSTKIDDING** [comment]
nvm, fixed it
