### ISSUE TITLE
Unhandled error: TypeError: Cannot read properties of undefined (reading 'attackDamage')

### ISSUE THREAD

**Issue by k-k-javascript** [codecombat/codecombat#7218]
The error happens in Cavern Survival.
This error message is shown when I use `hero.punch` to opponent's hero who is `guardian`.
![image](https://github.com/codecombat/codecombat/assets/156559169/e015fde8-6775-4d15-90a5-8adf59b6343b)
And this is console log.
```
Non-UserCodeError: TypeError: Cannot read properties of undefined (reading 'attackDamage')
TypeError: Cannot read properties of undefined (reading 'attackDamage')
    at CastsGoldShield.shieldedTakeDamage (eval at module.exports.World.loadClassFromCode (https://codecombat.com/javascripts/world.js:2:1763717), <anonymous>:93:32)
    at Punches.performPunch (eval at module.exports.World.loadClassFromCode (https://codecombat.com/javascripts/world.js:2:1763717), <anonymous>:65:17)
    at Punches.update (eval at module.exports.World.loadClassFromCode (https://codecombat.com/javascripts/world.js:2:1763717), <anonymous>:107:10)
    at e.exports.e.callChainedMethod (https://codecombat.com/javascripts/world.js:2:1742216)
    at e.h [as update] (https://codecombat.com/javascripts/world.js:2:2279111)
    at Existence.update (eval at module.exports.World.loadClassFromCode (https://codecombat.com/javascripts/world.js:2:1763717), <anonymous>:112:15)
    at e.exports.e.getNextFrame (https://codecombat.com/javascripts/world.js:2:1777860)
    at module.exports.World.getFrame (https://codecombat.com/javascripts/world.js:2:1755664)
    at module.exports.World.loadFrames (https://codecombat.com/javascripts/world.js:2:1757965)
    at a (https://codecombat.com/javascripts/world.js:2:1756922)
```
My code is here.
```javascript
var color = hero.pos.x < 80 ? "red" : "blue";
var enemyHeroString = color == "red" ? "Hero Placeholder 1" : "Hero Placeholder";
var enemyhero = hero.findEnemies().filter(function(unit){return unit == enemyHeroString;})[0];
while(hero.findEnemies().filter((unit) => unit.type == "door").length > 0){
    hero.attack(hero.findNearest(hero.findEnemies().filter((unit) => unit.type == "door")));
}
while(true) {
    if(hero.isReady("punch")) hero.punch(enemyhero);
    else hero.attack(enemyhero);
}
```

**Comment by nwinter** [comment]
Thanks, should be fixed noe.
